Projeto-Final-POO-master/171213_171178/src/java/managedbean/CategoriaMB.java
package managedbean;

import modelo.Categoria;
import servico.CategoriaService;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class CategoriaMB {
    private CategoriaService categoriaService = new CategoriaService();
    private Categoria cat = new Categoria();
    private Categoria selectedCat;
    
    public void salvar(){
        categoriaService.salvar(cat);
        cat = new Categoria();
    }
    
    public List<Categoria> getCategorias(){
        return categoriaService.getCategorias();
    }
    
    public Categoria getCat(){
        return cat;
    }
    
    public void setCat(Categoria Cat){
        this.cat = Cat;
    }
    
    public Categoria getSelectedCat(){
        return selectedCat;
    }
    
    public void setSelectedCat(Categoria selectedCat){
        this.selectedCat = selectedCat;
    }
    
    public void deleteCatg(){
        this.categoriaService.remover(selectedCat);
        selectedCat = null;
    }
    
}
    

    
    
    

Projeto-Final-POO-master/171213_171178/src/java/managedbean/ClienteMB.java
package managedbean;


import modelo.Cliente;
import servico.ClienteService;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class ClienteMB {
    private ClienteService clienteService = new ClienteService();
    private Cliente cli = new Cliente();
    private Cliente selectedClin;
    
    public void salvar(){
        clienteService.salvar(cli);
        cli = new Cliente();
    }
    
    public List<Cliente> getClientes(){
        return clienteService.getClientes();
    }
    
    public Cliente getCli(){
        return cli;
    }
    
    public void setCli(Cliente Cli){
        this.cli = Cli;
    }
    
    public Cliente getSelectedClin(){
        return selectedClin;
    }
    
    public void setSelectedClin(Cliente selectedClin){
        this.selectedClin = selectedClin;
    }
    
    public void deleteCli(){
        this.clienteService.remover(selectedClin);
        selectedClin = null;
    }
}
    

    
    
    

Projeto-Final-POO-master/171213_171178/src/java/managedbean/ExternoMB.java
package managedbean;

import modelo.ProdutoExportacao;
import servico.ProdutoService;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped

public class ExternoMB {
    private ProdutoService produtoService =  new ProdutoService();
    private ProdutoExportacao pro = new ProdutoExportacao();
    private ProdutoExportacao selectedPro;
    
    public void salvar(){
        produtoService.salvar(pro);
        pro = new ProdutoExportacao();
    }

    public ArrayList<ProdutoExportacao> getProdutos() {
                return produtoService.getProdutosExterno();
    }

    public void setProdutoService(ProdutoService produtoService) {
        this.produtoService = produtoService;
    }

    public ProdutoExportacao getPro() {
        return pro;
    }

    public void setPro(ProdutoExportacao pro) {
        this.pro = pro;
    }

    public ProdutoExportacao getSelectedPro() {
        return selectedPro;
    }

    public void setSelectedPro(ProdutoExportacao selectedPro) {
        this.selectedPro = selectedPro;
    }
    
    public void deleteProd(){
        this.produtoService.remover(selectedPro);
        selectedPro = null;
    }
}

Projeto-Final-POO-master/171213_171178/src/java/managedbean/InternoMB.java
package managedbean;

import modelo.ProdutoMercadoInterno;
import servico.ProdutoService;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped

public class InternoMB {
    private ProdutoService produtoService =  new ProdutoService();
    private ProdutoMercadoInterno pro = new ProdutoMercadoInterno();
    private ProdutoMercadoInterno selectedPro;
    
    public void salvar(){
        produtoService.salvar(pro);
        pro = new ProdutoMercadoInterno();
    }

    public ArrayList<ProdutoMercadoInterno> getProdutos() {
        return produtoService.getProdutosInterno();
    }

    public void setProdutoService(ProdutoService produtoService) {
        this.produtoService = produtoService;
    }

    public ProdutoMercadoInterno getPro() {
        return pro;
    }

    public void setPro(ProdutoMercadoInterno pro) {
        this.pro = pro;
    }

    public ProdutoMercadoInterno getSelectedPro() {
        return selectedPro;
    }

    public void setSelectedPro(ProdutoMercadoInterno selectedPro) {
        this.selectedPro = selectedPro;
    }

    public void deleteProd(){
        this.produtoService.remover(selectedPro);
        selectedPro = null;
    }
}

Projeto-Final-POO-master/171213_171178/src/java/managedbean/PedidoMB.java
package managedbean;

import modelo.Pedido;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import servico.PedidoService;

@ManagedBean
@SessionScoped
public class PedidoMB {
   private PedidoService pedidoService = new PedidoService();
   private Pedido ped = new Pedido();
   private Pedido selectedPedido;
   
   public void salvar(){
       pedidoService.salvar(ped);
       ped = new Pedido();
   }

    public ArrayList<Pedido> getPedidos() {
        return pedidoService.getListPedidos();
    }

    public Pedido getPed() {
        return ped;
    }

    public void setPed(Pedido ped) {
        this.ped = ped;
    }

    public Pedido getSelectedPedido() {
        return selectedPedido;
    }

    public void setSelectedPedido(Pedido selectedPedido) {
        this.selectedPedido = selectedPedido;
    }
   
    public void deletePdd(){
        this.pedidoService.remove(selectedPedido);
        selectedPedido = null;
    }
}

Projeto-Final-POO-master/171213_171178/web/Categoria.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    
    <ui:define name="title">
        <h:outputText value="Cadastro de Cliente"/> 
    </ui:define>
    
    <ui:define name="principal">
        <h1>Categoria</h1>
        <h:form id="formCat">
            <p:panelGrid columns="1">
                <p:outputLabel value="Descrição"/>
                <p:inputText value="#{categoriaMB.cat.descricao}"/>
            </p:panelGrid>
            <p:commandButton value="Salvar"
                             action="#{categoriaMB.salvar()}"
                             update=":formCat"/>
            
            <p:growl id="msgs" showDetail="true"/>
            <p:dataTable id="dataTableFunc"
                         var="c" value="#{categoriaMB.categorias}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         editable="true"
                         selection="#{categoriaMB.selectedCat}"
                         selectionMode="single"
                         rowKey="#{c.descricao}"
                         >
                
                <p:column headerText="Descrição">
                    <p:outputLabel value="#{c.descricao}"/>
                </p:column>
            </p:dataTable>
            <p:contextMenu for="dataTableFunc">
                <p:menuitem value="Delete" update="dataTableFunc" icon="pi pi-times" action="#{categoriaMB.deleteCatg}"/>
            </p:contextMenu>
        </h:form>
    </ui:define>
    
    
    
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/Cliente.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    
    <ui:define name="title">
        <h:outputText value="Cadastro de Cliente"/> 
    </ui:define>
    
    <ui:define name="principal">
        <h1>Cadastro de Clientes</h1>
        <h:form id="formClin">
            <p:panelGrid columns="2">
                <p:outputLabel value="Código"/>
                <p:inputText value="#{clienteMB.cli.codigo}"/>
                <p:outputLabel value="Nome"/>
                <p:inputText value="#{clienteMB.cli.nome}"/>
                <p:outputLabel value="Endereço"/>
                <p:inputText value="#{clienteMB.cli.endereco}"/>
                <p:outputLabel value="Telefone"/>
                <p:inputText value="#{clienteMB.cli.telefone}"/>
                <p:outputLabel for="formClin" value="Status" />
                        <p:selectOneMenu value="#{clienteMB.cli.status}" style="width:125px">
                            <f:selectItem itemLabel="Ativo" itemValue="1" />
                            <f:selectItem itemLabel="Inativo" itemValue="2" />
                            <f:selectItem itemLabel="Freemium" itemValue="3" />
                            <f:selectItem itemLabel="Premium" itemValue="4" />
                        </p:selectOneMenu>
                <p:outputLabel value="Limite"/>
                <p:inputText value="#{clienteMB.cli.limite}"/>
            </p:panelGrid>
            <p:commandButton value="Salvar"
                             action="#{clienteMB.salvar()}"
                             update=":formClin"/>
            
            <p:growl id="msgs" showDetail="true"/>
            <p:dataTable id="dataTableFunc"
                         var="c" value="#{clienteMB.clientes}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         editable="true"
                         selection="#{clienteMB.selectedClin}"
                         selectionMode="single"
                         rowKey="#{c.codigo}"
                         >
                
                <p:column headerText="Código">
                    <p:outputLabel value="#{c.codigo}"/>
                </p:column>
                <p:column headerText="Nome">
                    <p:outputLabel value="#{c.nome}"/>
                </p:column>
                  <p:column headerText="Endereço">
                      <p:outputLabel value="#{c.endereco}"/>
                </p:column>
                <p:column headerText="Telefone">
                      <p:outputLabel value="#{c.telefone}"/>
                </p:column>
                <p:column headerText="Status">
                    <p:outputLabel value="#{c.status}"/>
                </p:column>
                <p:column headerText="Limite">
                    <p:outputLabel value="#{c.limite}"/>
                </p:column>
            </p:dataTable>
            <p:contextMenu for="dataTableFunc">
                <p:menuitem value="Delete" update="dataTableFunc" icon="pi pi-times" action="#{clienteMB.deleteCli}"/>
            </p:contextMenu>
        </h:form>
    </ui:define>
    
    
    
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/Externo.xhtml
<ui:composition template="template.xhtml"
               xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
                
        <ui:define name="title">
		<h:outputText value="POO" />
	</ui:define>
    
	<ui:define name="principal">
            <h1>Produto Exportação</h1>
            <h:form id="formPro">
            <p:panelGrid columns="2">
                <p:outputLabel value="Código"/>
                <p:inputText value="#{externoMB.pro.codigo}"/>
                <p:outputLabel value="Nome"/>
                    <p:inputText value="#{externoMB.pro.nome}"/>
                <p:outputLabel for="formPro" value="Categoria" />
                <p:selectOneMenu value="#{externoMB.pro.categoria}"  converter="converterCategoria" style="width:125px" >
                    <f:selectItems value="#{categoriaMB.categorias}" var = "cat"
                                  itemValue="#{cat}" itemLabel="#{cat.descricao}" />
                </p:selectOneMenu>
               <p:outputLabel value="Preço"/>
                    <p:inputText value="#{externoMB.pro.preco}"/>
                    <p:outputLabel for="formPro" value="Moeda"/>
                <p:selectOneMenu value="#{externoMB.pro.moeda}" style="width:125px">
                        <f:selectItem itemLabel="Real" itemValue="1" />
                        <f:selectItem itemLabel="Dólar" itemValue="2" />
                        <f:selectItem itemLabel="Libra" itemValue="3" />
                        <f:selectItem itemLabel="Íenes" itemValue="4" />
                </p:selectOneMenu>
                <p:outputLabel value="Imposto"/>
                <p:inputText value="#{externoMB.pro.imposto}"/>
                <p:outputLabel value="Destino"/>
                <p:inputText value="#{externoMB.pro.destino}"/>
            </p:panelGrid>
            <p:commandButton value="Salvar"
                             action="#{externoMB.salvar()}"
                             update=":formPro"/>
            
            <p:growl id="msgs" showDetail="true"/>
                <p:dataTable id="dataTableFunc"
                             var="p" value="#{externoMB.produtos}"
                             rows="10"
                             paginator="true"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15"
                             editable="true"
                             editMode="cell"
                             widgetVar="cellProd"
                             selection="#{externoMB.selectedPro}"
                             selectionMode="single"
                             rowKey="#{p.codigo}"
                             >

                    <f:facet name="header">
                            Produtos Exportação
                    </f:facet>

                    <p:column headerText="Código">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.codigo}" /></f:facet>
                            <f:facet name="input"><p:inputText id="modelInput" value="#{p.codigo}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Nome">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.nome}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.nome}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                      <p:column headerText="Categoria">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.categoria}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.categoria}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Preço">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.preco}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.preco}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Moeda">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.moeda}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.moeda}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Imposto">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.imposto}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.imposto}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Destino">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.destino}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.destino}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                </p:dataTable>
                <p:contextMenu for="dataTableFunc">
                    <p:menuitem value="Delete" update="dataTableFunc" icon="pi pi-times" action="#{externoMB.deleteProd}"/>
                </p:contextMenu>
            </h:form>           
	</ui:define>
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/Interno.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
                
        <ui:define name="title">
		<h:outputText value="POO" />
	</ui:define>
    
	<ui:define name="principal">
            <h1>Produto Importação</h1>
            <h:form id="formPro1">
                <p:panelGrid columns="2">
                    <p:outputLabel value="Código"/>
                    <p:inputText value="#{internoMB.pro.codigo}"/>
                    <p:outputLabel value="Nome"/>
                    <p:inputText value="#{internoMB.pro.nome}"/>
                    <p:outputLabel for="formPro1" value="Categoria" />
                        <p:selectOneMenu value="#{internoMB.pro.categoria}"  converter="converterCategoria" style="width:125px">
                            <f:selectItems value="#{categoriaMB.categorias}" var = "cat"
                                  itemValue="#{cat}" itemLabel="#{cat.descricao}" />
                        </p:selectOneMenu>
                    <p:outputLabel value="Preço"/>
                    <p:inputText value="#{internoMB.pro.preco}"/>
                    <p:outputLabel for="formPro1" value="Moeda"/>
                    <p:selectOneMenu value="#{internoMB.pro.moeda}" style="width:125px">
                        <f:selectItem itemLabel="Real" itemValue="1" />
                        <f:selectItem itemLabel="Dólar" itemValue="2" />
                        <f:selectItem itemLabel="Libra" itemValue="3" />
                        <f:selectItem itemLabel="Íenes" itemValue="4" />
                     </p:selectOneMenu>
                    <p:outputLabel value="Imposto"/>
                    <p:inputText value="#{internoMB.pro.imposto}"/>
                    <p:outputLabel value="Incentivo"/>
                    <p:selectBooleanButton id="incentivo" value="#{internoMB.pro.incentivo}" onLabel="Sim" offLabel="Não" style="width:60px" />
                </p:panelGrid>
                
            <p:commandButton value="Salvar"
                             action="#{internoMB.salvar()}"
                             update=":formPro1"/>
            
            <p:growl id="msgs" showDetail="true"/>
            <p:dataTable id="dataTableFunc"
                         var="p" value="#{internoMB.produtos}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         editable="true"
                         editMode="cell"
                         widgetVar="cellProd"
                         selection="#{internoMB.selectedPro}"
                         selectionMode="single"
                         rowKey="#{p.codigo}"
                         >
                
                    <f:facet name="header">
                        Produtos Importação
                    </f:facet>
                
                
                    <p:column headerText="Código">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.codigo}" /></f:facet>
                            <f:facet name="input"><p:inputText id="modelInput" value="#{p.codigo}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Nome">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.nome}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.nome}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                      <p:column headerText="Categoria">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.categoria}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.categoria}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Preço">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.preco}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.preco}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Moeda">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.moeda}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.moeda}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Imposto">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.imposto}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.imposto}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column headerText="Incentivo">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{p.incentivo}" /></f:facet>
                            <f:facet name="input"><p:inputText value="#{p.incentivo}" style="width:96%"/></f:facet>
                        </p:cellEditor>
                    </p:column>
                
                </p:dataTable>
                
                <p:contextMenu for="dataTableFunc">
                    <p:menuitem value="Delete" update="dataTableFunc" icon="pi pi-times" action="#{internoMB.deleteProd}"/>
                </p:contextMenu>
            </h:form>           
	</ui:define>
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/Pedido.xhtml
<ui:composition template="template.xhtml"
               xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                
        <ui:define name="title">
		<h:outputText value="POO" />
	</ui:define>

	<ui:define name="principal">
            <h1>Pedidos</h1>
         
            
            <h:form id="formPed">
                <p:panelGrid columns="2">
                    <p:outputLabel value="Numero"/>
                    <p:inputText value="#{pedidoMB.ped.numero}"/>
                    <p:outputLabel  value="Data:"/>
                    <p:calendar value="#{pedidoMB.ped.date}" /> 
                    <p:outputLabel value="Itens Pedidos"/>
                    <p:inputText value="#{pedidoMB.ped.itens}"/> 
                    <p:outputLabel value="Cliente"/>
                    <p:inputText value="#{pedidoMB.ped.cliente}"/> 
                </p:panelGrid>
                
                <p:commandButton value="Salvar"
                                 action="#{pedidoMB.salvar()}"
                                 update=":formPed"/>
                    
                <p:growl id="msgs" showDetail="true"/>
                <p:dataTable id="dataTableFunc"
                             var="p" value="#{pedidoMB.pedidos}"
                         rows="10"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15"
                         editable="true"
                         selection="#{pedidoMB.selectedPedido}"
                         selectionMode="single"
                         rowKey="#{p.numero}"
                         >
                
                    <p:column headerText="Numero">
                        <p:outputLabel value="#{p.numero}"/>
                    </p:column>
                    <p:column headerText="Data">
                        <p:outputLabel value="#{p.date}" />
                    </p:column>
                    <p:column headerText="Itens Pedidos">
                        <p:outputLabel value="#{p.itens}"/>
                    </p:column>
                    <p:column headerText="Cliente">
                        <p:outputLabel value="#{p.cliente}"/>
                    </p:column>
                </p:dataTable>
                <p:contextMenu for="dataTableFunc">
                    <p:menuitem value="Delete" update="dataTableFunc" icon="pi pi-times" action="#{pedidoMB.deletePdd}"/>
                </p:contextMenu>
                
            </h:form>                        
            
	</ui:define>
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/Teste.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        Hello from FaceletsHello from Facelets
        Hello from Facelets
        Hello from Facelets
        
        
    </h:body>
</html>

Projeto-Final-POO-master/171213_171178/web/index.xhtml
<ui:composition template="template.xhtml"
               xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                
        <ui:define name="title">
		<h:outputText value="Início" />
	</ui:define>

	<ui:define name="principal">
			<h1>Início</h1>
	</ui:define>
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
	<h:form>
            <p:menubar>
                    <p:submenu label="Menu">
                            <p:submenu label="Cadastro">
                                    <p:submenu label="Produto">
                                            <p:menuitem value="Externo " url="/faces/Externo.xhtml" ></p:menuitem>
                                            <p:menuitem value="Interno"   url="/faces/Interno.xhtml"></p:menuitem>
                                    </p:submenu>
                                    <p:menuitem value="Cliente" url="/faces/Cliente.xhtml"></p:menuitem>
                            </p:submenu>

                            <p:menuitem value="Pedido"   url="/faces/Pedido.xhtml"></p:menuitem>
                            <p:menuitem value="Categoria"   url="/faces/Categoria.xhtml"></p:menuitem>
                                    <p:separator/>
                            <p:menuitem value="Helpme"></p:menuitem>
                    </p:submenu>
                
                    <p:submenu label="Help">
                            <p:menuitem value="About JournalDev"></p:menuitem>
                            <p:menuitem value="Contact Us"></p:menuitem>
                            <p:separator/>
                            <p:menuitem value="Help"></p:menuitem>
                    </p:submenu>
            </p:menubar>
    </h:form>
</ui:composition>

Projeto-Final-POO-master/171213_171178/web/rodape.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
                <p:outputLabel value="Gabriel Zonta da Costa R.A. - 171178 | Kevin de Souza Almeida R.A. - 171213" />
</ui:composition>